# Generated by Django 3.1.7 on 2021-03-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='play_DT',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
