# Generated by Django 3.1.7 on 2021-03-26 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('play_DT', models.DateTimeField(auto_created=True)),
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(default='Game!', max_length=500)),
                ('player_num', models.IntegerField()),
                ('question_num', models.IntegerField()),
                ('category', models.CharField(max_length=500)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueData',
            fields=[
                ('league_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('end_game_num', models.IntegerField(blank=True, null=True)),
                ('last_game_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.gamedata')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia.playerdata')),
            ],
        ),
        migrations.AddField(
            model_name='gamedata',
            name='league_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trivia.leaguedata'),
        ),
    ]
